Probable condescending language removed!
chec/commerce.js pull request #90
Opened 2020-10-09 18:38 UTC by mananchawla2005

2020-10-09 18:40 UTC, robbieaverill requested changes
Thanks for the PR. I'm happy to remove the "just" words in the getting started page, but the rest of your edits seem superfluous.

2020-10-09 18:40 UTC, robbieaverill commented on docs/04_Concepts.md
> +Commerce.js SDK includes all client side endpoints, so you can use them in your client-facing
```suggestion
Commerce.js SDK includes all client side endpoints, so you can use them quickly and easily in your client-facing
```

I don't agree that this is condescending

2020-10-09 18:40 UTC, robbieaverill commented on docs/04_Concepts.md
> +using your sandbox key until you're ready to deploy your new project live. Orders created with sandbox keys can be cleared from the Chec Dashboard, and will automatically use the "Test Gateway" for p
```suggestion
using your sandbox key until you're ready to deploy your new project live. Orders created with sandbox keys can easily
be cleared from the Chec Dashboard, and will automatically use the "Test Gateway" for payment processing.
```

There's no improvement here

2020-10-09 18:40 UTC, robbieaverill commented on docs/05_Full-SDK-Reference.md
> +**Commerce.js** is a JavaScript SDK built on top of the **Chec Platform** to allow for interfacing with the **Chec
```suggestion
**Commerce.js** is a JavaScript SDK built on top of the **Chec Platform** to allow for easy interfacing with the **Chec
```

2020-10-09 18:41 UTC, robbieaverill approved these changes
Thanks

2020-10-09 18:41 UTC, merged

2020-10-09 18:57 UTC, mananchawla2005 commented
Always happy to help 🙂. A small request also. Kindly add hacktoberfest accepted label to this pr as it was not related to any issue. It was independent so as per rules label is required.

2020-10-09 18:58 UTC, robbieaverill commented
Jump over and get some Chec swag while you're at it!

https://commercejs.com/docs/hacktoberfest

2020-10-10 10:30 UTC, mananchawla2005 commented
@robbieaverill yeah but dont have debit/credit card. Anyways loved contributing :-)

2020-10-10 19:09 UTC, robbieaverill commented
@mananchawla2005 it's free, you don't need a card!